using System.Data.Common;
using MicroMax.Server.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace MicroMax.Server.Data;

public static class DatabaseBootstrapper
{
    private const string LegacyUserPassword = "ChangeMe123!";

    public static async Task InitializeAsync(MicroMaxDbContext db, IPasswordHasher<AppUser> passwordHasher)
    {
        await db.Database.EnsureCreatedAsync();
        await EnsureRolesAsync(db);
        // await UpgradeLegacySchemaAsync(db, passwordHasher);
        await DemoDataSeeder.SeedAsync(db, passwordHasher);
    }

    private static async Task EnsureRolesAsync(MicroMaxDbContext db)
    {
        if (await db.Roles.AnyAsync())
        {
            return;
        }

        db.Roles.AddRange(
            new Role { Code = SystemRoleCodes.Admin, Name = "Администратор склада" },
            new Role { Code = SystemRoleCodes.Worker, Name = "Сотрудник склада" },
            new Role { Code = SystemRoleCodes.Viewer, Name = "Наблюдатель" });
        await db.SaveChangesAsync();
    }

    private static async Task UpgradeLegacySchemaAsync(MicroMaxDbContext db, IPasswordHasher<AppUser> passwordHasher)
    {
        await using var connection = db.Database.GetDbConnection();
        if (connection.State != System.Data.ConnectionState.Open)
        {
            await connection.OpenAsync();
        }

        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "Roles" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "Code" character varying(32) NOT NULL,
                "Name" character varying(120) NOT NULL
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_Roles_Code" ON "Roles" ("Code");
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "WarehouseUsers" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "WarehouseId" integer NOT NULL,
                "UserId" integer NOT NULL,
                "RoleId" integer NOT NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_WarehouseUsers_Warehouses_WarehouseId" FOREIGN KEY ("WarehouseId") REFERENCES "Warehouses" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_WarehouseUsers_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE CASCADE,
                CONSTRAINT "FK_WarehouseUsers_Roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES "Roles" ("Id") ON DELETE CASCADE
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_WarehouseUsers_WarehouseId_UserId" ON "WarehouseUsers" ("WarehouseId", "UserId");
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE TABLE IF NOT EXISTS "RefreshTokens" (
                "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "UserId" integer NOT NULL,
                "TokenHash" character varying(128) NOT NULL,
                "ExpiresAt" timestamp with time zone NOT NULL,
                "RevokedAt" timestamp with time zone NULL,
                "CreatedAt" timestamp with time zone NOT NULL,
                CONSTRAINT "FK_RefreshTokens_AppUsers_UserId" FOREIGN KEY ("UserId") REFERENCES "AppUsers" ("Id") ON DELETE CASCADE
            );
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE UNIQUE INDEX IF NOT EXISTS "IX_RefreshTokens_TokenHash" ON "RefreshTokens" ("TokenHash");
            """);
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "AppUsers" ADD COLUMN IF NOT EXISTS "Email" character varying(256) NOT NULL DEFAULT '';
            ALTER TABLE "AppUsers" ADD COLUMN IF NOT EXISTS "PasswordHash" character varying(512) NOT NULL DEFAULT '';
            ALTER TABLE "AppUsers" ADD COLUMN IF NOT EXISTS "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW();
            ALTER TABLE "AppUsers" ADD COLUMN IF NOT EXISTS "IsActive" boolean NOT NULL DEFAULT TRUE;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            ALTER TABLE "WarehouseOperations" ADD COLUMN IF NOT EXISTS "WarehouseId" integer NOT NULL DEFAULT 0;
            """);
        await db.Database.ExecuteSqlRawAsync("""
            CREATE INDEX IF NOT EXISTS "IX_WarehouseOperations_WarehouseId" ON "WarehouseOperations" ("WarehouseId");
            """);

        if (await ColumnExistsAsync(connection, "AppUsers", "Login"))
        {
            await db.Database.ExecuteSqlRawAsync("""
                UPDATE "AppUsers"
                SET "Email" = CASE
                    WHEN POSITION('@' IN COALESCE("Login", '')) > 0 THEN LOWER("Login")
                    ELSE LOWER("Login") || '@local.micromax'
                END
                WHERE COALESCE("Email", '') = '';
                """);
        }

        await db.Database.ExecuteSqlRawAsync("""
            UPDATE "WarehouseOperations" o
            SET "WarehouseId" = COALESCE(
                (SELECT z."WarehouseId"
                 FROM "StorageCells" c
                 JOIN "StorageZones" z ON z."Id" = c."StorageZoneId"
                 WHERE c."Id" = o."TargetCellId"),
                (SELECT z."WarehouseId"
                 FROM "StorageCells" c
                 JOIN "StorageZones" z ON z."Id" = c."StorageZoneId"
                 WHERE c."Id" = o."SourceCellId"),
                "WarehouseId")
            WHERE "WarehouseId" = 0;
            """);

        if (await TableExistsAsync(connection, "UserRoles") && await ColumnExistsAsync(connection, "AppUsers", "UserRoleId"))
        {
            await db.Database.ExecuteSqlRawAsync("""
                INSERT INTO "WarehouseUsers" ("WarehouseId", "UserId", "RoleId", "CreatedAt")
                SELECT w."Id",
                       u."Id",
                       r."Id",
                       NOW()
                FROM "AppUsers" u
                CROSS JOIN "Warehouses" w
                JOIN "UserRoles" ur ON ur."Id" = u."UserRoleId"
                JOIN "Roles" r ON r."Code" = CASE
                    WHEN UPPER(ur."Name") = 'ADMIN' OR ur."Name" ILIKE '%админ%' THEN 'ADMIN'
                    WHEN UPPER(ur."Name") = 'WORKER' OR ur."Name" ILIKE '%опера%' OR ur."Name" ILIKE '%сотруд%' THEN 'WORKER'
                    ELSE 'VIEWER'
                END
                WHERE NOT EXISTS (
                    SELECT 1
                    FROM "WarehouseUsers" wu
                    WHERE wu."WarehouseId" = w."Id" AND wu."UserId" = u."Id");
                """);
        }

        var usersWithoutPassword = await db.AppUsers
            .Where(x => string.IsNullOrWhiteSpace(x.PasswordHash))
            .ToListAsync();

        foreach (var user in usersWithoutPassword)
        {
            if (string.IsNullOrWhiteSpace(user.Email))
            {
                user.Email = $"user{user.Id}@local.micromax";
            }

            user.PasswordHash = passwordHasher.HashPassword(user, LegacyUserPassword);
            user.IsActive = true;
        }

        if (usersWithoutPassword.Count > 0)
        {
            await db.SaveChangesAsync();
        }
    }

    private static async Task<bool> TableExistsAsync(DbConnection connection, string tableName)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT 1
            FROM information_schema.tables
            WHERE table_schema = 'public' AND table_name = @tableName
            LIMIT 1;
            """;
        AddParameter(command, "@tableName", tableName);
        return await command.ExecuteScalarAsync() is not null;
    }

    private static async Task<bool> ColumnExistsAsync(DbConnection connection, string tableName, string columnName)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = """
            SELECT 1
            FROM information_schema.columns
            WHERE table_schema = 'public' AND table_name = @tableName AND column_name = @columnName
            LIMIT 1;
            """;
        AddParameter(command, "@tableName", tableName);
        AddParameter(command, "@columnName", columnName);
        return await command.ExecuteScalarAsync() is not null;
    }

    private static void AddParameter(DbCommand command, string name, object value)
    {
        var parameter = command.CreateParameter();
        parameter.ParameterName = name;
        parameter.Value = value;
        command.Parameters.Add(parameter);
    }
}
